### ISSUE TITLE
IDEA: Using bs4 for HTML parsing?

### ISSUE THREAD

**Issue by lfernsy** [Tikolu/nettaB#4]
You could use [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) for HTML parsing, It would probably be easier to develop for and may even be _slightly_ faster.

But you would have to install it, as it is not included in Python by default:
  `pip install beautifulsoup4`

PS. Do you also agree that "Beautiful Soup" is a strange name? (Off topic)

**Comment by Tikolu** [comment]
I would like to make nettaB really simple to use for people with beginner Python skills, and therefore would like to keep the amount of libraries required to a minimum. And unless Beautiful Soup (yes it does have a pretty weird name) has some major advantage, I would want to stick with `html` since it's pre-included in Python.

On the other hand, we're already importing `requests` so we might as well import another library.

I don't know. What do you think?

**Comment by lfernsy** [comment]
I think I an going to make a bs4 rewrite of SETTI and you can tell me what you think of it.

I will also benchmark it to see how long both versions take to download a sample page. (bs4 rewrite and original)

**Comment by Tikolu** [comment]
Sure. I'm open to anything that can improve this library.

**Comment by lfernsy** [comment]
Here's the result, i'll do that benchmark now.: [bs4 version](https://github.com/skipz36/nettaB/blob/bs4/nettaB.py)

**Comment by lfernsy** [comment]
|       Regular nettaB       |         bs4 edition        |
|:--------------------------:|:--------------------------:|
| 976 ms +/- 1.75 s per loop | 378 ms +/- 207 ms per loop |

**Comment by Tikolu** [comment]
Oh wow, I didn't even imagine this could be the bottleneck...

**Comment by lfernsy** [comment]
Should I start a pull request for the bs4 version?

**Comment by lfernsy** [comment]
Also, SETTI IS a library, so avoiding other library's should not be much of a concern.

**Comment by Tikolu** [comment]
I made you a collaborator, so you can chan change the code without pull requests. (At least, that is what I think I did)

**Comment by Tikolu** [comment]
I merged your bs4 version.
